CREATE TABLE IF NOT EXISTS posts (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    title varchar(255) DEFAULT NULL,
    content longtext,
    slug varchar(255) DEFAULT NULL,
    draft tinyint(1) NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    published_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;