CREATE TABLE IF NOT EXISTS tags (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name varchar(255) UNIQUE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;