CREATE TABLE IF NOT EXISTS posts_tags (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    post_id VARCHAR(255) NOT NULL,
    tag_id VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE post_tag_index (post_id, tag_id),
    CONSTRAINT fk_post_id
    FOREIGN KEY (post_id)
    REFERENCES posts (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tag_id
    FOREIGN KEY (tag_id)
    REFERENCES tags (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;