ALTER TABLE users ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE posts ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE tags ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tags ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE posts_tags ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts_tags ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;