apiVersion: v1
kind: Service
metadata:
  name: blog-server
  labels:
    app: blog-server
spec:
  selector:
    app: blog-server
  ports:
    - name: http
      port: 80
      targetPort: 1323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-server
  labels:
    app: blog-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-server
  template:
    metadata:
      labels:
        app: blog-server
    spec:
      containers:
        - name: blog-server
          image: le0tk0k/blog-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1323
          env:
            - name: ENV
              value: "prod"
            - name: MYSQL_ROOT_PASSWORD
              value: "myblogrootpassword"
            - name: MYSQL_DATABASE
              value: "blog_prod"
            - name: MYSQL_USER
              value: "le0tk0k"
            - name: MYSQL_PASSWORD
              value: "myblogpassword"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: TZ
              value: "Asia/Tokyo"
            - name: CORS_ALLOW_ORIGIN
              value: "http://blog-front"
            - name: AUTH_KEY
              value: "myblogsecret"